# .nixpacks/config.toml
version = 1

[phases.setup]
pkgs = [
  "php82",
  "php82Packages.composer",
  "nodejs-18_x",
  "npm"
]

[phases.install]
cmds = [
  "composer install --no-dev --ignore-platform-reqs",
  "npm install --legacy-peer-deps --no-audit --fund=false"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"